### ISSUE TITLE
Confusing evaluation compute metric(auc, f1) methods

### ISSUE THREAD

**Issue by calliwen** [siyongxu/GNUD#3]
In this code, you compute metric(auc, f1) for eval and test(latest version deleted) on the (mean of **batch**-auc/f1), it's confusion for me.   The better way to compute metrics is on mean of user-auc/f1.

 It is fairer to calculate the evaluation metrics based on each user,  even though you want to sampling neg-item for a user. 

If you compute the metric based on batch samples,  the metric value will change with the order of sample organization.
It's Doubtful !!!

**Comment by siyongxu** [comment]
In experiments, we set the number of epochs as 1 and adopt ealry stop to avoid over-fitting for graph-based method.
And in our sample data, the number of negtive samples is the same as positve samples, thus we treat it as a binary classification and compute the metric based on batch samples like some other recommenadtion methods . For all the baselines we feed the same sample data.
Your suggestion is also great and we are taking more experiments.
